tsconfig.app.json

- 팀원 소영의 ts config 오류로인해` tsconfig.app.json` 파일에 `"composite": true,` 옵션을 추가했습니다~
관련 이슈 없습니다.
Closes #️⃣
npm run dev로 실행 되는지 확인했습니다.

chore: <composite": true> ts 설정 추가

---

src/hooks/useSignUp.tsx

- supabase 라이브러리를 설치하고, 클라이언트 파일을 생성했습니다. (src/services/supabase.js)
- supabase의 회원가입 커스텀 훅으로 만들어 다양한 페이지에서 사용할 수 있도록 구현했습니다.
---
- 코드
```
import { supabase } from "@/services/supabase";
import { useState } from "react";
export function useSignUp() {
const [loading, setLoading] = useState<boolean>(false); // 로딩 상태
const [error, setError] = useState<string | null>(null); // 에러 상태
const signUp = async (email: string, password: string) => {
setLoading(true);
setError(null);
try {
const { data, error } = await supabase.auth.signUp({
email,
password,
options: {
emailRedirectTo: "http://localhost:3000", // 이메일 인증 후 리디렉션 주소
},
});
if (error) throw error;
return data;
} catch (err: unknown) {
if (err instanceof Error) {
// 타입 가드. 에러가 정말 존재 하는지.
setError(err.message);
} else {
setError("회원가입 시도 중 …
```

feat: 회원가입 커스텀 훅 제작

---

src/router/routes.tsx

merge test

---

src/hooks/usePasswordReset.tsx

- supabase auth 비밀번호 재설정 커스텀 훅을 제작했습니다.
- 해당 이슈는 라우터와 재설정 페이지가 다 만들어진 다음에 테스트 후 종료하겠습니다~
Closes #️⃣
페이지 만들어지면 그때 테스트해보겠습니다.

feat(auth): 비밀번호 재설정 커스텀 훅 제작 (#20)

---

src/components/Input.tsx
src/components/SubmitButton.tsx
src/components/styles/form.module.css

- input 창 ui -> 추후, placeholder에 맞게 조사 판별하는 훅 추가 예정
- submit button ui  -> Props에 클릭 이벤트 함수 추가해야 함
Closes #️⃣8

ui (input, submit):  공통 입력창, 버튼 창 추가(#8)

---

src/App.tsx
src/components/styles/fixedLayout.module.css
src/hooks/useNumberStep.tsx
src/pages/Games/Number/NumberPlay.tsx
src/pages/Games/Number/components/Card.module.css
src/pages/Games/Number/components/CardBack.tsx
src/pages/Games/Number/components/CardFront.tsx
src/pages/Games/Number/components/NumberCard.tsx
src/pages/Games/Number/components/getRandomCard.ts
src/router/routes.tsx
src/styles/global.css

feat: 숫자 컴포넌트 생성(#64), fix: 글로벌 css변경 

---

src/App.tsx
src/components/styles/fixedLayout.module.css
src/pages/Login/Login.module.css
src/pages/SignUp/SignUp.module.css
src/styles/global.css

- 글로벌 레이아웃 조정했습니다.
관련 이슈 없습니다.
Closes #️⃣

[fix] 글로벌 css 수정 (#null)

---

src/pages/Games/GamesPage.module.css
src/pages/Games/components/GameResult.tsx
src/pages/Games/components/styles/FinishGame.module.css
src/pages/Games/components/styles/GameResult.module.css
src/pages/Games/components/styles/StartCountdown.module.css
src/pages/Games/components/styles/StartGame.module.css

-  수정된 global.css에 맞춰 레이아웃 수정했습니다.
- 게임 결과창에 이미지가 늦게 로딩되어 레이아웃이 깨지는걸 수정했습니다.
- 이미지 로딩은 늦지만 결과창 박스 크기를 고정하여 창 크기 자체는 일정하게 유지됩니다.
Closes #73 

[fix] 게임 공통 컴포넌트 레이아웃 깨짐 해결(#73)

---

src/pages/SignUp/SignUp.module.css
src/pages/SignUp/SignUp.tsx

- 기존 이메일 인증 과정을 제거함
- 에러처리 ui 수정
Closes #75 

[feat] 회원가입 이메일 인증 제거 (#75)

---

src/styles/global.css

- 글로벌 css 배경색 white -> light-gray로 변경 
Closes #98 

ui(globalCSS): 배경색 추가

---

src/components/layout/Navigation.tsx
src/components/styles/fixedLayout.module.css

- 네비바 아이콘 클릭시 색상 변경 
- 마이페이지 아이콘 태그 통일화 필요 
Closes #99 

[ui](navigation): 아이콘 클릭시 색상 변경 추가

---

src/pages/Games/LetterColor/components/LetterColorPlay.tsx
src/pages/Games/LetterColor/components/letterColorPlay.module.css
src/pages/Games/components/PlayPage.tsx
src/pages/Games/components/SubmitAnswer.tsx
src/pages/Games/components/styles/startGame.module.css
src/pages/Games/components/styles/submitAnswer.module.css

- 윈도우 환경에서 노란 글씨색 스트로크 적용이 획마다 되던것 고쳤습니다.
- -webkit-text-stroke => text-shadow
- 글자색 맞추기 게임 로직에 Timer, AnswerSubmit,CurrentScore 컴포넌트 적용했습니다
Closes #106 

[fix]글자색 맞추기 게임 윈도우 stroke(테두리) 에러 외 컴포넌트 적용(#106)

---

src/components/layout/Header.tsx
src/pages/Home/components/styles/gameCard.module.css
src/pages/Home/components/styles/style.module.css
src/styles/global.css

- 팀원들과 화면 공유하면서 받은 피드백을 반영했습니다.
- 홈페이지에서는 뒤로가기 버튼이 안보이게 수정했습니다.
- global.css에 스크롤 생길때 ui 깨지는거 방지하는 코드 넣었습니다.
관련 이슈 없습니다.

[feat] 홈페이지 피드백 반영 (#null)

---

src/pages/Games/components/DynamicTimer.tsx
src/pages/Games/components/styles/dynamicTimer.module.css
src/styles/global.css

- 타이머 싱크 이슈 해결 했습니다.
- 모바일 뷰에서 뉴로가 화면 밖으로 나가버리는 버그도 수정했습니다.
: global.css에 가로 스크롤 방지 코드로 해결 했습니다.
Closes #126 

[fix] 타이머 싱크 이슈 해결 (#126)

---

src/pages/Games/Choseong/choseong.module.css
src/pages/Games/LetterColor/components/letterColorPlay.module.css
src/styles/global.css

- 글로벌 css 건드니까 홈페이지가 깨지네용.. 언능 다시 돌려놓고 하위 컴포넌트에 각각 지정해주는 방식으로 수정했습니다.
관련 이슈 없습니다.

[fix] 타이머 뉴로 박치기 이슈 재 수정 (#null)

---

src/pages/Games/components/styles/tutorial.module.css

- 게임 튜토리얼 모달 width 수정
Closes #️⃣

[refactor] 게임 튜토리얼 width 수정 (#null)

---

src/hooks/useCountdownTimer.tsx
src/hooks/useNumberStep.tsx
src/pages/Games/Number/components/NumberCardPlay.tsx
src/types/game.type.ts
src/types/numberCardSetting.ts
src/types/numberGame.type.ts
src/utils/numberGameProcess.ts

- numberGameProcess 파일 추가 : 게임 진행에 필요한 오답 처리, 정답 처리 함수 유틸화
- game.type.ts 파일 추가 : 게임 공통 타입 전역 타입으로 모듈화 
- useCountdownTimer 컴포넌트 추가 : 게임 시작전 시간 화면에 보여줌 
- numberCardSetting 파일 추가: 라운드마다 변경되는 카드 상태 유틸화 
Closes #136 

[refactor]: 숫자를 외워라 게임 함수, 기능별 파일 분리(#136)

---

package-lock.json
package.json
src/common/layout/Spinner.tsx
src/common/styles/spinner.module.css
src/pages/MyPage/MyPage.tsx

- react-spinner 설치필요
- react spinner 사용해 로딩중에 사용할 컴포넌트 생성했습니다.
Closes #️⃣

[feat] 로딩화면에 사용 할 Spinner 컴포넌트 제작(#null)

---

src/api/service/qna/insertQna.ts
src/pages/Qna/QnaLayout.tsx
src/pages/Qna/components/Question.tsx
src/pages/Qna/index.tsx
src/pages/Qna/write/index.tsx
src/pages/Qna/write/writeQna.module.css
src/router/routes.tsx

- 문의 작성 페이지 ui
- 작성 기능 
- api 연동 
Closes #134

[feat] 문의작성 페이지  완성 

---

src/pages/Games/common/PlayPage.tsx
src/pages/Games/common/styles/finishGame.module.css
src/pages/Games/common/styles/playPage.module.css
src/pages/Games/common/styles/startGame.module.css

- 게임플레이가 완료되었는데도 게임 상태가 리셋되지 않는 경우 발견
- 게임이 새로 시작할때마다 게임 전체를 다시 마운트 시켜 해결
- PlayPage 전체를 감싸는 div에 key값을 주고 key의 상태를 변화시켜 렌더링 유도
- clean up 함수를 사용할 수 있었으나 게임마다 초기화가 필요한 요소가 다르고, 유지해야 하는 상태도 없어 깔끔하게 전부를 리렌더링 하는 방식 선택
Closes #154 

[fix] 다시하기 눌러도 게임 리셋이 안되는 버그 해결(#154)

---

src/api/service/qna/getQnaList.ts
src/api/service/qna/getQnaListData.ts
src/common/post/PostCard.tsx
src/pages/MyPage/MyPage.tsx
src/pages/Qna/index.tsx
src/utils/getFormatDate.ts

- 고객 문의 조회 api 연동
Closes #160 

[api]고객 문의 조회 api 연동 (#160)

---

src/api/service/qna/getQnaListData.ts
src/common/post/PostCard.tsx

- is_answer로 되어있어서 데이터가 변경 안되는 에러 해결 
- is_answer -> is_answered로 변경 
Closes #️⃣

fix(qna): 고객문의 조회 데이터 필드 변수명 변경

---

src/api/service/notice/getNoticeData.ts
src/common/post/PostCard.tsx
src/common/post/postCard.module.css
src/pages/Notice/index.tsx
src/pages/Qna/index.tsx

- 공지사항 조회api 연동
- 디테일 정보 데이터 css 줄바꿈 추가 
Closes #️⃣97

[feat] 공지사항 조회 api 연동 (#97)

---

src/pages/MyPage/MyPage.tsx

- 마이페이지 공지사항 1개로 필터링 후, api 연동
Closes #️⃣

api(mypage): 공지사항 api 연동(#146)

---

src/pages/MyPage/MyPage.tsx
src/pages/Notice/index.tsx
src/pages/Qna/index.tsx

- 고객 문의 데이터 없을시 loading spinner 보여줌
- 공지 사항 데이터 없을시 loading spinner 보여줌
- 마이페이지 공지사항 key 지정 -> 키 없음 에러 해결 
Closes #165 

[refactor]고객 문의 , 공지 사항 데이터 없을 시 loading spinner(#165)

---

src/pages/Games/common/PlayPage.tsx
src/pages/Home/components/GameCard.tsx

- 개발용 콘솔로그 지움.
- svg 카멜케이스 에러 제거.
관련이슈 없습니다.

[refactor] 콘솔로그 지우고 svg 에러 제거 (#null)

---

src/common/modals/Ranking/RankingItem.tsx

- 랭킹 모달의 게이지가 조금만 차오르는 버그를 수정했습니다.
Closes #186 

[fix] 랭킹 모달 게이지 버그 수정 (#186)

---

src/pages/SignUp/SignUp.module.css

- 회원가입 페이지 -> 체크박스와 동의하기 문구 정렬 맞춤
Closes #173 

ui: 회원가입 - 동의하기와 체크박스 정렬 맞추기(#173)

---

src/hooks/useSignUp.ts
src/pages/Home/index.tsx

- 홈 이미지 경로 하드코딩에서 임포트로 변경
Closes #️⃣

[fix] : 홈 이미지 임포트로 변경

---

package-lock.json
package.json
src/pages/Games/common/GameResult.tsx
src/utils/confetti.ts

- 이제 게임 결과에 별모양 효과가 나옵니다.
Closes #214 

[feat] 결과창에서 폭죽 효과 추가 (#214)

---

src/styles/global.css

- 배경 색상을 좀 더 밝은 톤으로 수정하였습니다.
- 쉐도우 효과를 주어서 배경과 구분감 있게 구현했습니다.
Closes #216 

[ui] 배경 색상 변경, 쉐도우 효과 추가 (#216)

---

src/utils/isExistWord.ts

- 초성 퀴즈에서 단어 탐색 로직을 수정했습니다.
- 기존 로직은 약 7만개의 단어를 순차적으로 탐색하여 유저가 입력단 단어가 사전에 존재하는지를 탐색했습니다.
- 이러한 로직은 상대적으로 앞쪽에 위치한 단어는 빠르게 탐색, 상대적으로 뒤쪽에 위치하는 단어는 느리게 탐색되는 현상이 발생합니다.
- 실제 유저가 몸으로 느낄 수 있는 수준은 아니지만 게임 최적화를 위해 이분 탐색을 추가했습니다.
- 선형탐색 (Linear Search)
: 최소 탐색 횟수: 1번 (첫 번째 요소가 찾는 단어)
: 최악 탐색 횟수: 70,000번 (마지막 요소가 찾는 단어, 또는 없는 단어)
: 평균 탐색 횟수: 35,000번
- 이분탐색 (Binary Search)
: 최소 탐색 횟수: 1번 (중앙값이 찾는 단어)
: 최악 탐색 횟수: 17번 (log₂ 70,000 ≈ 16.09)
: 평균 탐색 횟수: 약 16번
따라서 거의 모든 단어들이 비슷한 탐색 횟수로 찾아지기 때문에 더욱 최적화된 로직이 완성되었습니다.
Closes #218 

[feat] 이분 탐색 로직 추가 (#218)

---

src/common/post/PostCard.tsx
src/common/post/postCard.module.css

- [fix] 고객 문의 토글 버튼 클릭시 사용자가 작성한 내용 화면에 추가 
Closes #220

[fix] 고객 문의 토글 버튼 클릭시 사용자가 작성한 내용 안 보이는 버그 해결(#220)

---

src/common/form/Input.tsx
src/hooks/usePasswordReset.ts
src/pages/FindAccount/components/ResetPasswordPending.tsx
src/pages/FindAccount/index.tsx
src/pages/SignUp/components/styles/pendingEmail.module.css
src/router/routes.tsx

- 게정찾기 라우팅 연결을 깜빡했습니다...
- 죄송합니다..
- 정상적으로 계정찾기가 가능합니다.
Closes #222 

[feat] 계정찾기  라우팅 연결 (#222)

---

src/common/post/PostCard.tsx
src/common/post/postCard.module.css

fix(qna): 고객문의 목록 ui 간격 수정

---

README.md

- 깃허브에서 리드미 정렬이 되지 않는 문제를 해결했습니다.
Closes #️⃣

[docs] 리드미 정렬 문제 수정 (#null)
